### ISSUE TITLE
404 NOT Found

### ISSUE THREAD

**Issue by ChaofanTao** [yangyuexiong/Flask_BestPractices#3]
Hi, I am new to the Flask. I have followed your guide in ReadMe that set the virtual env and env variable "FLASK_ENV" and "STARTUP_MODE". Then I run the run.py (masOS).

the terminal returns:
`时间:2020-06-10 23:32:47.230466
操作系统:Darwin
项目路径:/Flask_BestPractices
当前环境:development
启动方式:pyc
threading: 4623654336
当前进程id: 22563
父进程id: 17994
< ------------------------------------------------------------------ >
 * Serving Flask app "ApplicationExample" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:9999/ (Press CTRL+C to quit)
 * Restarting with stat
Linux或Darwin配置文件:/Flask_BestPractices/config/dev.ini
< ------------------------------------------------------------------ >
时间:2020-06-10 23:32:47.761835
操作系统:Darwin
项目路径:/Flask_BestPractices
当前环境:development
启动方式:pyc
threading: 4398337472
当前进程id: 22566
父进程id: 22563
< ------------------------------------------------------------------ >
 * Debugger is active!
 * Debugger PIN: 205-568-464`

When I click http://0.0.0.0:9999/ , the webset returns:
'
{
  "code": 404, 
  "data": "GET /", 
  "message": "HTTPException:\u3010404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.\u3011"
}
'

I do not know what is my wrong? I would also like to know the meaning of the value "pyc" and "ter" for Variable "STARTUP_MODE".

Thank you !

**Comment by yangyuexiong** [comment]
因为没有根目录的url处理函数，需要http://0.0.0.0:9999/api/ 或者 http://0.0.0.0:9999/cms/，或者你可以添加：‘/’ 的处理函数，详细请查阅，reedme。感谢你的提问。
