### ISSUE TITLE
Api result might also return a kind of response for webhooks

### ISSUE THREAD

**Issue by MistaIA** [yangyuexiong/Flask_BestPractices#9]
Only if not already done somewhere I missed, with a little refactor it looks like this:

```python
def api_result(code=None, message=None, data=None, details=None, status=None):
    result = {
        'code': code,
        'message': message,
        'data': data,
        'details': details,
        'status': status
    }

    if not result['data']:
        result.pop('data')
    if not result['details']:
        result.pop('details')
    if not result['status']:
        result.pop('status')

    return jsonify(result)


def webhook_result(code=None, message=None, data=None, status=None, details=None):
    return api_result(
        code=code, message=message, data=data, details=details, status=status
    ), code

```

https://github.com/yangyuexiong/Flask_BestPractices/blob/006bca54e9b655d534c2e3e64cf62047223cdec2/common/libs/api_result.py#L13

**Comment by yangyuexiong** [comment]
def webhook_result(code=None, message=None, data=None, status=None, details=None):
    return api_result(
        code=code, message=message, data=data, details=details, status=status
    ), code

你的代码是没有问题的，但是在实际业务使用中code更多的是以其他数字来定义例如：1000001等，如果是这样的，以上代码返回的code将不会被HTTP识别导致响应错误，使用webhook_result需要注意code符合HTTP CODE。
